language: java
dist: xenial
os: linux
jdk:
- openjdk8
- openjdk11
- oraclejdk11
# Requires Gradle 6.3 https://github.com/gradle/gradle/issues/10248
#- openjdk14
#- oraclejdk14

script:
- ./gradlew build

deploy:
- provider: releases
  edge: true
  token: ${GITHUB_API_KEY}
  file_glob: true
  file:
    - ./build/libs/commons-configuration2-jackson-*.jar
  on:
    repo: Virtlink/commons-configuration2-jackson
    branch: master
    tags: true
    jdk: openjdk8
- provider: script
  edge: true
  script: ./gradlew bintrayUpload
  on:
    repo: Virtlink/commons-configuration2-jackson
    branch: master
    tags: true
    jdk: openjdk8
