---
name: Build

on:  # yamllint disable-line rule:truthy
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    name: Build
    strategy:
      matrix:
        os: [ubuntu-latest]
        java: [11, 17]
        gradle: [wrapper]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Validate Gradle wrapper
        uses: gradle/actions/wrapper-validation@v3
      - name: Setup JDK ${{ matrix.java }}
        uses: actions/setup-java@v4
        with:
          java-version: ${{ matrix.java }}
          distribution: 'temurin'
      - name: Setup Gradle ${{ matrix.gradle }}
        uses: gradle/actions/setup-gradle@v3
        with:
          gradle-version: ${{ matrix.gradle }}
          build-scan-publish: true
          build-scan-terms-of-use-url: "https://gradle.com/help/legal-terms-of-use"
          build-scan-terms-of-use-agree: "yes"
      - name: Build
        run: |
          gradle build
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
